lang_name: "Deutsch"
title: "Lehrstuhl für Mechatronik"
introduction: "Wir freuen uns sehr über die Zusammenarbeit mit den Studenten und wir möchten euch kurz vorstellen, in welchen Themengebieten wir uns besonders über eure Unterstützung freuen würden. Kommt gerne mit euren Ideen und Vorstellungen vorbei und wir suchen gemeinsam nach Möglichkeiten, wie ihr eure Abschlussarbeiten, Seminararbeiten, Forschungs- und Projektmodule bei uns erledigen könnt. Für Fragen stehen wir euch jederzeit zur Verfügung."
copyright: "© Universität Augsburg"
contact: "Kontakt"
additional_info: "Zusätzliche Informationen"
sb: "Seminararbeit Bachelor"
sm: "Seminararbeit Master"
fm: "Forschungsmodul"
pm: "Projektmodul"
ba: "Bachelorarbeit"
ma: "Masterarbeit"
reset: "Filter zurücksetzen"