lang_name: "English"
title: "Chair of Scientific Computing in Mechatronics"
introduction: "We are very happy to work with students and would like to briefly introduce you to the subject areas in which we would particularly appreciate your support. Feel free to drop by with your ideas and concepts and together we will look for ways in which you can complete your final theses, seminar papers, research and project modules with us. We are always available to answer your questions."
copyright: "© University of Augsburg"
contact: "Contact"
additional_info: "Additional info"
sb: "Seminar Bachelor"
sm: "Seminar Master"
fm: "Research Module"
pm: "Project Module"
ba: "Bachelor Thesis"
ma: "Master Thesis"
reset: "Reset Filter"